name: Python CI  # You can name your workflow

on:
  push:
    branches: [ main ]  # Trigger on push to main branch; adjust as needed
  pull_request:
    branches: [ main ]  # Trigger on PRs to main branch; adjust as needed

jobs:
  build:  # This is a job identifier; you can name it as you like
    runs-on: ubuntu-latest  # Specifies the runner

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Ensure pytest is installed
          pip install -r requirements.txt  # Install other dependencies
      - name: Run tests
        run: |
          pytest
